name: nesy23
channels:
        - conda-forge
        - defaults
dependencies:
        - hydra-core
        - openai
        - numpy
        - pandas
        - python==3.10.6
        - seaborn
        - torchtext==0.13.1
        - wandb

